src/Android/Properties/AndroidManifest.xml, src/Core/Models/Domain/Domain.cs, src/iOS.Autofill/Info.plist, src/iOS.Extension/Info.plist, src/iOS/Info.plist
In the addon, it is possible to create empty URI field. These empty fields
make the app crash, since we try to decipher them down the line.
=> fix: Do not crash when uri field is null or whitespace

src/Android/Properties/AndroidManifest.xml
Followed https://firebase.google.com/docs/analytics/configure-data-collection?platform=android
By default Firebase collect data. We have to explicitly remove that. 
I didn't test it since I can't build on my machine yet
=> fix: Disable Firebase Analytics

src/iOS.Autofill/iOS.Autofill.csproj, src/iOS.Extension/iOS.Extension.csproj
Implicit `Newtonsoft.json` references were handled by `HockeySDK` but broke after `HockeySDK` removal on commit 1064354842c189e9026181add180f39f83e65c58.
This bug is not visible on existing dev environments as the old nuget package may still be referenced in `bin/` and `obj/` folders.
But it appears after trying to compile a fresh project. It can also be reproduced by deleting all `bin/` and `obj/` folders from the solution.
Note that `Newtonsoft.json` package has been added to `iOS.Autofill` and `iOS.Extension` projects although it is only used by the `Core` project.
This is because `Core` is a "standard/PCL" library that is independent of the platform. So every project that uses `Core` needs to include a platform specific version of `Newtonsoft.json`.
=> fix: add missing nuget packages for Newtonsoft.Json

src/App/Resources/AppResources.en-GB.resx, src/App/Resources/AppResources.fr.resx, src/App/Resources/AppResources.resx
Some users have to use their organization password and not their "cozy" password. The previous wording would introduce ambiguity (cozy password vs organization password).
=> fix: change password hints to prevent ambiguity on which password to use

src/Android/Android.csproj, src/iOS.Autofill/iOS.Autofill.csproj, src/iOS.Extension/iOS.Extension.csproj, src/iOS/iOS.csproj
Provisioning profiles were still referencing Bitwarden ones so they have been replaced by Cozy's profiles.
Also some compilation parameters were updated by Visual Studio (`EmbedAssembliesIntoApk` for android and `SdkOnly` for MtouchLink). Those were needed to compile using the `publish` tool.
=> fix: set correct provisioning profiles and compile options for 'publish'

src/Android/Properties/AndroidManifest.xml, src/iOS.Autofill/Info.plist, src/iOS.Extension/Info.plist, src/iOS/Info.plist
Updated versions before publishing on stores.
=> chore: bump to 2.4.1

src/App/Pages/Settings/SettingsPage/SettingsPageViewModel.cs, src/Core/Abstractions/ICozyClientService.cs, src/Core/Core.csproj, src/Core/Services/CozyClientService.cs, src/Core/Utilities/UrlHelper.cs, test/Core.Test/Utilities/UrlHelperTests.cs
Like for the extension, the mobile app was not handling subdomain type correctly. Also it was still using the old route parameters (`/installation/import` vs `/vault?action=import`)
This PR fixes those problems
=> fix: correctly handle settings/import link generation

src/App/Controls/CipherViewCell/CipherViewCell.xaml
On `grouping` view ciphers subtitles are truncated if too long
A supernumerary column declaration was breaking the grid and ciphers
subtitles were truncated if longer than the cipher's name, even if
there was enough place to display them completly
Now ciphers subtitles take all available space and are truncated only
if larger than the screen
This reverts part of d3d7e0b8988ac7707bdd32eac2aa879ff7feb924
____________
Before:
After:
=> fix: correctly handle ciphers login ellipsis

src/App/Pages/Vault/AddEditPage.xaml.cs, src/App/Pages/Vault/ViewPage.xaml.cs
This PR removes `Attachments` menu from iOS cipher view and edit pages
It was removed from Android earlier but I didn't notice that iOS version implements it in a different way
___
Attachments are not implemented on Cozy Stack
Related commit: 15ceddf64d4a29dac2a158ded56c8d5e65819e7d
=> fix: disable attachments from iOS

src/App/Resources/AppResources.fr.resx
We chose to translate `move` to `valider` as the button is here to
confirm the action
`déplacer` is redundant with the page title `Déplacer dans un dossier`
and also is longer than `valider`. So it seems to be a better choice
for a clean interface
=> fix: translate `move` confirm button when moving a cipher to a folder

src/App/Pages/Vault/AddEditPage.xaml, src/App/Pages/Vault/AddEditPageViewModel.cs
Current workflow does not allow to edit cipher's folder before its
creation
This feature is disabled on cipher's creation screen until we adapt the
workflow
___
Future solution would be to edit the SharePage in order to:
- take a boolean that would be true if we open the page un "create" mode
- only set the cipher's organizationId without calling the server when validating the choice
- then the AddEdit page would have to call the correct share method after cipher's creation (or maybe just create it if we can encrypt it directly with the org key).
Another option would be to create a new Page for that process instead of adding complexity to SharePage.
=> fix: remove folder list on cipher creation

src/App/Resources/AppResources.fr.resx, src/App/Resources/AppResources.resx
This PR change the description of `move to folder` popup in order to fit Cozy's spec
=> feat: edit `move to folder` description

src/iOS.Core/Controllers/LockPasswordViewController.cs
Contrary to Android version, iOS uses a native project to display
autofill pages
Unlock form from iOS autofill is now using Inverted theme color scheme
⚠️ I didn't find how to change the clear button's color (current version is black). Any suggestion would be appreciated.
=> feat: set inverted theme for iOS autofill `unlock` form

src/Core/Services/CozyClientService.cs
In previous commit `GetURLForApp()` has been refactored to handle
nested domains vs flat domains
During this refactor, params have been forced with values from
`SettingsPageViewModel.Import()` method which was a mistake
This broke `SettingsPageViewModel.TwoStepAsync()` method that would
redirect to Cozy Pass import page instead of Cozy Settings page
Params are now correctly passed to `UrlHelper.GenerateWebLink()`
Related commit: b3d84a116ccac7117cc38f70736a5c41a4755ac1
=> fix: correctly handle params in `CozyClientService.GetURLForApp()`

src/App/Pages/Vault/AddEditPage.xaml, src/App/Resources/AppResources.fr.resx, src/App/Resources/AppResources.resx
Notes were disabled to avoid confusion with Cozy Notes
We enable them again but named as `Description`
Related commit: 0c2fd0d0560fc19df15560751b6176b7ad7e8080
=> feat: re-enable notes

src/App/Resources/AppResources.fr.resx, src/App/Resources/AppResources.resx
Users cannot create a shared folder from the Mobile app, so we add
instruction on how to do it from the web interface
=> feat: improve `move to folder` description

src/App/Pages/Vault/AddEditPage.xaml
Disable the Help button on AddEditPage's `PasswordPrompt` as we don't
have any help page at Cozy that describes this feature
=> fix: remove the help button on `PasswordPrompt` field

src/App/Pages/Settings/SettingsPage/SettingsPage.xaml
When a setting label is single line and its setting value is single line, everything is displayed correctly
When a setting label is multi line and its value is single word, then
the value may not succeed to require enough space and so it may wrap in
the middle of the word and it becomes multi line
When a setting label is multi line and its value is multi words, then
the value succeed to require enough space to be displayed correctly
With `MinimumWidthRequest=100` and `LineBreakMode=WordWrap`, all three
previous cases are displayed correctly without excessive wrapping
___
⚠️ this solution is a hack more than a real solution. Hopefully the `MinimumWidthRequest` does not force the label to have a width of 100 if it is smaller. Sadly I don't really understand why this work 🙃  
It has been …
=> fix: avoid word wrapping for single word settings values

src/App/Pages/Accounts/LockPage.xaml
Frame component has a different behavior when running on iOS compared
to Android
When `CornerRadius` property is set, then Android applies a crop on
the image which is contained inside of the rounded corners
On iOS this crop is not applied until `IsClippedToBounds` property is
set to `True`
=> fix: force image crop on iOS on Lock page

CHANGELOG.md, src/Android/Properties/AndroidManifest.xml, src/iOS.Autofill/Info.plist, src/iOS.Extension/Info.plist, src/iOS/Info.plist
Bump to `3.0.2` in order to release https://github.com/cozy/cozy-pass-mobile/pull/75 fix on iOS
`3.0.2` will only be released on iOS as Android isn't impacted by the fix. However both platforms' versions have been bumped
=> feat: bump version to 3.0.2

src/App/App.csproj, src/App/Pages/Send/SendGroupingsPage/SendGroupingsPage.xaml, src/App/Pages/Settings/SettingsPage/SettingsPageViewModel.cs, src/App/Pages/Vault/GroupingsPage/GroupingsPage.xaml
On iOS 15+ scroll views would use a different calculation algorithm for
auto cell sizes, which may result in infinite loops and app crash
This commit is retrieved from bitwarden official project
Related PR: bitwarden/mobile#1842
=> fix: Prevent app crash when scrolling grouped collection view in iOS 15+

CHANGELOG.md, src/Android/Properties/AndroidManifest.xml, src/Android/Resources/xml/accessibilityservice.xml, src/App/Pages/Settings/AutofillServicesPage.xaml, src/App/Pages/Settings/AutofillServicesPage.xaml.cs, src/App/Pages/Settings/AutofillServicesPageViewModel.cs, src/App/Resources/AppResources.Designer.cs, src/App/Resources/AppResources.fr.resx, src/App/Resources/AppResources.resx, src/iOS.Autofill/Info.plist, src/iOS.Extension/Info.plist, src/iOS/Info.plist
This PR bumps the app to 3.0.4
Now that we're targeting API 32 we're required to comply with Google
new policy regarding non-accessibility apps using accessibility
services. This PR adds the disclosure and consent prompt as described
on the help page.
https://support.google.com/googleplay/android-developer/answer/10964491
This PR is a partial cherry pick from Bitwarden's changes
Related PR: bitwarden/mobile#2102
Related PR: bitwarden/mobile#2104
=> feat: bump version to 3.0.4 and add accessibility service disclosure prompt for Android

src/Core/Abstractions/ITokenService.cs, src/Core/Core.csproj, src/Core/Models/Request/TokenRequest.cs, src/Core/Services/ApiService.cs, src/Core/Services/AuthService.cs, src/Core/Services/CozyClientService.cs, src/Core/Services/TokenService.cs
With current implementation, the Cozy's Connected Devices list would display `Cozy Pass`, `Cozy Pass (2)`,  `Cozy Pass (3)` etc for each new connected device
To improve this, we add the device's name to the client name. So it would become `Cozy Pass (Claude's phone)`, `Cozy Pass (iPhone 13)` etc
____
We want the Cozy's OAuth client to be deleted when the user logs out from the app
With current implementation, the OAuth client can be deleted only if the logout is done in the same runtime session than when the login has been done. If the app is closed, then the `clientId` and `registrationAccessToken` are lost and we won't be able to delete it anymore
While `clientId` can be recovered from the persisted token, the `registrationAccessToken` cannot be recovered. It is definitively lost
To …
=> feat: Add device's name to OAuth client name and fix logout

src/App/App.xaml.cs, src/App/Pages/Accounts/HomePage.xaml.cs, src/App/Utilities/CozyEnvironmentOverride.cs, src/Core/Abstractions/ICozyClouderyEnvService.cs, src/Core/Services/CozyClouderyEnvService.cs, src/Core/Utilities/ServiceContainer.cs
We want to be able to override ClouderyEnv by using an universal link or a scheme link
The app should be able to intercept links containing `cozy_env_override` keyword and extract new ClouderyEnv configuration from it
This feature is needed for debugging purpose so we display a Xamarin alert when a link is intercepted and the configuration is overriden
This feature is based on the same one we implemented on Flagship app project
Related PR: cozy/cozy-flagship-app#654
=> feat: Implement ClouderyEnv override using links

.gitignore, docs/dev.md, src/Android/Android.csproj, src/Android/MainActivity.cs, src/App/App.xaml.cs, src/iOS/Entitlements.plist
This PR configures both Android and iOS projects to support Universal Links (the app only supported `cozypass://` scheme until now)
I also introduced a new debug.keystore file that now should be extracted from our password-store so we can declare its signature in the https://links.mycozy.cloud/.well-known/assetlinks.json file (instructions have been added to `docs/dev.md` file)
=> feat: Add universal links support to Android and iOS

src/Android/Android.csproj, src/Android/MainActivity.cs, src/Android/MainApplication.cs, src/Android/Properties/AndroidManifest.xml, src/Android/Services/ClipboardService.cs, src/Android/Services/DeviceActionService.cs, src/App/Pages/Generator/GeneratorHistoryPageViewModel.cs, src/App/Pages/Generator/GeneratorPageViewModel.cs, src/App/Pages/Settings/SettingsPage/SettingsPageViewModel.cs, src/App/Pages/Vault/PasswordHistoryPageViewModel.cs, src/App/Pages/Vault/ViewPageViewModel.cs, src/App/Services/MobilePlatformUtilsService.cs, src/App/Utilities/AppHelpers.cs, src/Core/Abstractions/IClipboardService.cs, src/Core/Abstractions/IPlatformUtilsService.cs, src/iOS.Core/Services/ClipboardService.cs, src/iOS.Core/Utilities/iOSCoreHelpers.cs, src/iOS.Core/iOS.Core.csproj, src/iOS/AppDelegate.cs
PlayStore will soon require apps to target SDK 33 (Android 13)
Android 13 now displays copied text in a system popup. This is problematic as the copied text can contain sensitive data
(i.e. passwords), so we want the OS to display the "copied" popup without displaying the clear text
More info:
https://developer.android.com/about/versions/13/features/copy-paste
Related PR: bitwarden/mobile#1947
Related PR: bitwarden/mobile#1679
=> feat: Change Android TargetSDK for 33 and adapt clipboard management to fit new Android 13 behaviour

src/Core/Services/CozyClouderyEnvService.cs
In #86 we reworked the login worflow in order to display the Cloudery web pages instead of a native form. This would allow the user to login by entering their email adresse. The received email would then be opened in a browser which would then redirect to a `cozypass://` scheme
With this scenario, in some environments (i.e. Firefox mobile browser) the user would be redirected to their Cozy login web form instead of being redirect to the Cozy Pass mobile application
This is due to the manager's JS code that would fail opening the `cozypass://` scheme and then redirects to the web login form
In #91 we implemented support to Universal Links, but we did not change the Cloudery url to use them instead of the Scheme
By changing the scheme of an Universal Link, then the login by email scenario …
=> [VO-390] fix: Use universal links on LoginByEmail scenario
